### ISSUE TITLE
elfinder

### ISSUE THREAD

**Issue by JohnSmall** [antonzaytsev/elrte-rails#4]
The gem works brilliantly. Thanks for the work you've done.

But I can't upload files. When I try to upload a file I get the error 'invalid backend configuration'.

The solution might be contained in the phrase ' and check eltre editor instead of it with elfinder support'
I'm not sure what that means. If you can explain then I'll help you with your English to write the explanation more clearly.

It could be that the message 'invalid backend configuration' means that I have to set things up on the backend as described in the documentation for the rails-elfinder gem.

**Comment by antonzaytsev** [comment]
Hey!

Glad the gem was helpful for you. I did changes in readme file, hope now it more clear, it not - please send me pull request with your changes in it, I will be happy to receive any changes from you :)

About your problem,
message "Invalid backend configuration" displaying when server responded with 404 error, that's why problem can be with routes.

Did you do all steps described in readme ?
Check your routes file for line "Elrte.routes(self)"
